backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images/blog
public_folder: /images/blog
collections:
  - name: 'post'
    label: 'Blog'
    folder: 'content'
    create: true
    type: "post"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {labe: 'Image', name: 'thumbnail', widget: 'image'}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
